[package]
name = "factorize"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
num-bigint = "0.2.2"
structopt = "0.3.3"
mod_exp = "1.0.1"